# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Varun Rau
tagline:          'A Cool Guy'
description:      'Computer Science Student at UC Berkeley. Loves Programming, People, and Pies.'
url:              http://varunrau.com

author:
  name:           'Varun Rau'
  url:            https://varunrau.com

paginate:         5
